name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Decode SSH Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > key.pem
        chmod 400 key.pem

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          sudo su
          cd /home/ubuntu/log || mkdir /home/ubuntu/log && cd /home/ubuntu/log

          # Clone the repo if not already present
          if [ ! -d ".git" ]; then
            git clone https://github.com/Kishorepec/logalyze.git .
          fi

          # Pull latest changes
          git pull origin master

          # Build and restart Docker container
          docker stop jolly_shirley || true
          docker rm jolly_shirley || true
          docker build -t log .
          docker run -d --restart always -p 8080:3000 --env-file .env --name log log
        EOF

